### ISSUE TITLE
Results Table 1

### ISSUE THREAD

**Issue by gabrieldernbach** [zihao-wang/spred#1]
First of all, thanks for sharing your work!

I was reading the version of your paper on https://arxiv.org/pdf/2210.01212.pdf
and am particularly interested in the results you present in Table 1.
```Prediction accuracy for the gene selection task for cancer diagnosis and survival time prediction```

In the $f_n$ case did you use an MLP in the style presented in this repository?
That is
* no bias term
* no batch normalization

I understand that you use early stopping and SGD for optimization. Did you also include a lr-scheduler in these experiments?

**Comment by zihao-wang** [comment]
Hi, thanks for your interest, and sorry for the late reply.

I am sorry for the incomplete code release. The cancer classification you mentioned in the paper is actually implemented in another previous repository.

https://github.com/zihao-wang/redundancy_is_sparsity

The code to run the experiments is implemented in 

https://github.com/zihao-wang/redundancy_is_sparsity/blob/master/cancer_sparse_classification.py 

The model that you are interested in is implemented in 

https://github.com/zihao-wang/redundancy_is_sparsity/blob/08e8cd6e02be157a915723dd348fa22cf6f63a1a/models.py#L203

I am working on the merging of different codebases

**Comment by zihao-wang** [comment]
This issue is fixed after following version

https://github.com/zihao-wang/spred/commit/299b426c7279fbece7adc343324b4cad9c13db26
